######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 15 17:42:22 2010
######################################################################


DEPENDENCY_LIBRARIES = common
include(../lib_dep.pri)

QT += network xml
CONFIG += DEBUG
TEMPLATE = app
TARGET = ../Serverd
DEPENDPATH += .
INCLUDEPATH += . ../common
LIBS += -L../common -lcommon

# Input
HEADERS += Serverd.h Serverd.cpp
SOURCES += main_serverd.cpp Serverd.cpp
