######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 15 17:42:22 2010
######################################################################


DEPENDENCY_LIBRARIES = src
include(../lib_dep.pri)

QT += network
CONFIG += DEBUG
TEMPLATE = app
TARGET = ../Serverd
DEPENDPATH += .
INCLUDEPATH += . ../src
LIBS += -L../src -lsrc

# Input
HEADERS += Serverd.h Serverd.cpp
SOURCES += main_serverd.cpp Serverd.cpp
